name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: get-env-var
        run: echo "Environment is:$URL"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Use variables
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          TENANT: ${{ secrets.TENANT }}
          TEST: "test string"
        run: |
          echo "DOMAIN: $DOMAIN"
          echo "TENANT: $TENANT"
          echo "TEST: TEST"
      - name: Test domain is not set
        run: exit 1
        if: ${{ !env.DOMAIN }}

      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30