name: Scenarios

on:
  workflow_dispatch:
    inputs:
      run_on_tenants:
        description: Tenants
        type: choice
        default: 'database'
        options:
          - all
          - database
          - acme
          - claroty
          - aviatrix
      run_on_env:
        description: Environments
        type: choice
        default: 'database'
        options:
          - all
          - database
          - production
          - staging
      run_scenarios:
        description: Scenarios
        type: choice
        default: 'database'
        options:
          - all
          - database
          - arr_net_top_accuracy
          - pnl_net_calculation
          - pnl_10x_values_check

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Use variables
        env:
          ENV_NAME: ${{ inputs.environment }}
          DOMAIN: ${{ vars.DOMAIN }}
          TENANT: ${{ vars.TENANT }}
        run: |
          echo "ENV_NAME: $ENV_NAME"
          echo "DOMAIN: $DOMAIN"
          echo "TENANT: $TENANT"

      - name: Check domain set
        run: |
          if [[ "${{ vars.DOMAIN }}" == "" ]]; then exit 1; else echo "OK"; fi

      - name: Check user set
        run: |
          if [[ "${{ secrets.TEST_USER }}" == "" ]]; then exit 1; else echo "OK"; fi

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          DOMAIN: ${{ vars.DOMAIN }}
          TENANT: ${{ vars.TENANT }}
          TEST_USER: ${{ secrets.TEST_USER }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

        run: npx playwright test scenario

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
